name: Weather App CI

env:
  NODE_VERSION: 18.14.0

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome107
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{env.NODE_VERSION}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Unit Tests
        run: npm test
      - name: E2E Tests
        run: npx uuv e2e --generateHtmlReport --generateJunitReport || cat ./uuv/reports/e2e/junit-report.xml
      - name: Test Report
        uses: dorny/test-reporter@v1.9.1
        if: success() || failure()
        with:
          name: Report - E2E Tests - Playwright
          path: ./uuv/reports/e2e/junit-report.xml
          reporter: jest-junit
      - run: npm run build --if-present -- --base-href=/weather-app/
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@main
        with:
         name: github-pages
         path: dist/weather-app

  publish:
    if: github.ref == 'refs/heads/main'
    needs: [ build-and-test ]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
